version: '3'

services:
  bobo_beats_comment_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'

  comment_app:
    build: .
    volumes:
      - .:/src/app
    depends_on: 
      - 'bobo_beats_comment_db'
    environment:
      DB_HOST: 'FILL ME IN'
      DB_USER: 'FILL ME IN'
      DB_PASS: 'FILL ME IN'
      DB_NAME: 'FILL ME IN'
    ports:
      - '4001:3001'

