
create database if not exists bobo_beats_comment_app;

use bobo_beats_comment_app;

drop table if exists users;

create table users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  avatar_url VARCHAR(128) NOT NULL,
  follower_count INT
);

INSERT INTO users 
  (username, avatar_url, follower_count) VALUES
("Amparo Kihn", "https://s3.amazonaws.com/uifaces/faces/twitter/vicivadeline/128.jpg", 81),
("Obie Weimann", "https://s3.amazonaws.com/uifaces/faces/twitter/smaczny/128.jpg", 30),
("Thomas Renner", "https://s3.amazonaws.com/uifaces/faces/twitter/axel/128.jpg", 43),
("Terrill Sporer", "https://s3.amazonaws.com/uifaces/faces/twitter/manigm/128.jpg", 47),
("Tyreek Spencer", "https://s3.amazonaws.com/uifaces/faces/twitter/bruno_mart/128.jpg", 13),
("Aron Cassin", "https://s3.amazonaws.com/uifaces/faces/twitter/sementiy/128.jpg", 59),
("Leone Altenwerth", "https://s3.amazonaws.com/uifaces/faces/twitter/matkins/128.jpg", 2),
("Bryon Frami", "https://s3.amazonaws.com/uifaces/faces/twitter/helderleal/128.jpg", 48),
("Brooks Beier", "https://s3.amazonaws.com/uifaces/faces/twitter/laurengray/128.jpg", 40),
("Joy Hartmann", "https://s3.amazonaws.com/uifaces/faces/twitter/homka/128.jpg", 47),
("Zora Kub", "https://s3.amazonaws.com/uifaces/faces/twitter/jeremiespoken/128.jpg", 20),
("Shanon Jacobson", "https://s3.amazonaws.com/uifaces/faces/twitter/isnifer/128.jpg", 45),
("Beulah Lang", "https://s3.amazonaws.com/uifaces/faces/twitter/antongenkin/128.jpg", 72),
("Lia Eichmann", "https://s3.amazonaws.com/uifaces/faces/twitter/thomasgeisen/128.jpg", 25),
("Anibal Borer", "https://s3.amazonaws.com/uifaces/faces/twitter/bergmartin/128.jpg", 29),
("Junior Ledner", "https://s3.amazonaws.com/uifaces/faces/twitter/therealmarvin/128.jpg", 4),
("Ruthe Sipes", "https://s3.amazonaws.com/uifaces/faces/twitter/iamsteffen/128.jpg", 14),
("Nannie Strosin", "https://s3.amazonaws.com/uifaces/faces/twitter/michaelcolenso/128.jpg", 92),
("Reilly O'Hara", "https://s3.amazonaws.com/uifaces/faces/twitter/plasticine/128.jpg", 65),
("Katrine Nader", "https://s3.amazonaws.com/uifaces/faces/twitter/pyronite/128.jpg", 22),
("Deanna Moen", "https://s3.amazonaws.com/uifaces/faces/twitter/imsoper/128.jpg", 53),
("Brady Smith", "https://s3.amazonaws.com/uifaces/faces/twitter/matthewkay_/128.jpg", 79),
("Lynn Predovic", "https://s3.amazonaws.com/uifaces/faces/twitter/marlinjayakody/128.jpg", 59),
("Matilda Eichmann", "https://s3.amazonaws.com/uifaces/faces/twitter/dgajjar/128.jpg", 70),
("Don Rohan", "https://s3.amazonaws.com/uifaces/faces/twitter/txcx/128.jpg", 90),
("Carlo Langosh", "https://s3.amazonaws.com/uifaces/faces/twitter/malgordon/128.jpg", 35),
("Libbie Schimmel", "https://s3.amazonaws.com/uifaces/faces/twitter/stefooo/128.jpg", 22),
("Harold Harber", "https://s3.amazonaws.com/uifaces/faces/twitter/jwalter14/128.jpg", 52),
("Jovany Bradtke", "https://s3.amazonaws.com/uifaces/faces/twitter/robergd/128.jpg", 75),
("Flavio Keebler", "https://s3.amazonaws.com/uifaces/faces/twitter/trueblood_33/128.jpg", 30),
("Octavia Hamill", "https://s3.amazonaws.com/uifaces/faces/twitter/carlosm/128.jpg", 77),
("Graham Quigley", "https://s3.amazonaws.com/uifaces/faces/twitter/rikas/128.jpg", 90),
("Verdie Maggio", "https://s3.amazonaws.com/uifaces/faces/twitter/heycamtaylor/128.jpg", 49),
("Hazle Breitenberg", "https://s3.amazonaws.com/uifaces/faces/twitter/ripplemdk/128.jpg", 98),
("Pascale Purdy", "https://s3.amazonaws.com/uifaces/faces/twitter/adrienths/128.jpg", 15),
("Jailyn Metz", "https://s3.amazonaws.com/uifaces/faces/twitter/timmillwood/128.jpg", 49),
("Marielle Predovic", "https://s3.amazonaws.com/uifaces/faces/twitter/matt3224/128.jpg", 90),
("Syble Oberbrunner", "https://s3.amazonaws.com/uifaces/faces/twitter/herbigt/128.jpg", 90),
("Theodore Keebler", "https://s3.amazonaws.com/uifaces/faces/twitter/geneseleznev/128.jpg", 63),
("Annie Marvin", "https://s3.amazonaws.com/uifaces/faces/twitter/pmeissner/128.jpg", 97),
("Bradley Reichert", "https://s3.amazonaws.com/uifaces/faces/twitter/ostirbu/128.jpg", 85),
("Lenora Harvey", "https://s3.amazonaws.com/uifaces/faces/twitter/bigmancho/128.jpg", 64),
("Brandy Smith", "https://s3.amazonaws.com/uifaces/faces/twitter/anasnakawa/128.jpg", 54),
("Dessie Sipes", "https://s3.amazonaws.com/uifaces/faces/twitter/conspirator/128.jpg", 24),
("Katheryn Schimmel", "https://s3.amazonaws.com/uifaces/faces/twitter/nomidesigns/128.jpg", 31),
("John Bednar", "https://s3.amazonaws.com/uifaces/faces/twitter/dgajjar/128.jpg", 70),
("Tia Mosciski", "https://s3.amazonaws.com/uifaces/faces/twitter/andrewcohen/128.jpg", 94),
("Cecil Lehner", "https://s3.amazonaws.com/uifaces/faces/twitter/baumann_alex/128.jpg", 21),
("Mason Spinka", "https://s3.amazonaws.com/uifaces/faces/twitter/guischmitt/128.jpg", 41),
("Lilly Fay", "https://s3.amazonaws.com/uifaces/faces/twitter/seyedhossein1/128.jpg", 80),
("Orin Hamill", "https://s3.amazonaws.com/uifaces/faces/twitter/davidmerrique/128.jpg", 77),
("Kole Kulas", "https://s3.amazonaws.com/uifaces/faces/twitter/superoutman/128.jpg", 87),
("Guadalupe Veum", "https://s3.amazonaws.com/uifaces/faces/twitter/thaodang17/128.jpg", 73),
("Meredith Stokes", "https://s3.amazonaws.com/uifaces/faces/twitter/eduardostuart/128.jpg", 33),
("Richard Farrell", "https://s3.amazonaws.com/uifaces/faces/twitter/puzik/128.jpg", 80),
("Emilie Ankunding", "https://s3.amazonaws.com/uifaces/faces/twitter/jodytaggart/128.jpg", 82),
("Jonas Pfannerstill", "https://s3.amazonaws.com/uifaces/faces/twitter/nsamoylov/128.jpg", 52),
("Tabitha Jacobson", "https://s3.amazonaws.com/uifaces/faces/twitter/BroumiYoussef/128.jpg", 61),
("Rebecca Blick", "https://s3.amazonaws.com/uifaces/faces/twitter/cynthiasavard/128.jpg", 82),
("Jaime Luettgen", "https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg", 69),
("Issac Heller", "https://s3.amazonaws.com/uifaces/faces/twitter/mylesb/128.jpg", 35),
("Reta Lakin", "https://s3.amazonaws.com/uifaces/faces/twitter/fiterik/128.jpg", 9),
("Carleton Hudson", "https://s3.amazonaws.com/uifaces/faces/twitter/edkf/128.jpg", 56),
("Kirk Wilkinson", "https://s3.amazonaws.com/uifaces/faces/twitter/kerihenare/128.jpg", 65),
("Ellis Ryan", "https://s3.amazonaws.com/uifaces/faces/twitter/lepinski/128.jpg", 91),
("Laurie Krajcik", "https://s3.amazonaws.com/uifaces/faces/twitter/shinze/128.jpg", 9),
("Maurine Herman", "https://s3.amazonaws.com/uifaces/faces/twitter/justinrob/128.jpg", 5),
("Jaron Quitzon", "https://s3.amazonaws.com/uifaces/faces/twitter/barputro/128.jpg", 92),
("Alanna Gulgowski", "https://s3.amazonaws.com/uifaces/faces/twitter/dansowter/128.jpg", 88),
("Emery Labadie", "https://s3.amazonaws.com/uifaces/faces/twitter/ultragex/128.jpg", 75),
("Domenico Ruecker", "https://s3.amazonaws.com/uifaces/faces/twitter/juanmamartinez/128.jpg", 2),
("Cathryn Schmitt", "https://s3.amazonaws.com/uifaces/faces/twitter/_kkga/128.jpg", 83),
("Kamron Nader", "https://s3.amazonaws.com/uifaces/faces/twitter/osmond/128.jpg", 30),
("Ova Watsica", "https://s3.amazonaws.com/uifaces/faces/twitter/gregrwilkinson/128.jpg", 6),
("Laurine Ortiz", "https://s3.amazonaws.com/uifaces/faces/twitter/osmanince/128.jpg", 14),
("Marcelina Glover", "https://s3.amazonaws.com/uifaces/faces/twitter/canapud/128.jpg", 20),
("Avis Prohaska", "https://s3.amazonaws.com/uifaces/faces/twitter/reabo101/128.jpg", 17),
("Juliet Reinger", "https://s3.amazonaws.com/uifaces/faces/twitter/ruehldesign/128.jpg", 87),
("Gwen Emard", "https://s3.amazonaws.com/uifaces/faces/twitter/fluidbrush/128.jpg", 67),
("Rhiannon Feeney", "https://s3.amazonaws.com/uifaces/faces/twitter/caspergrl/128.jpg", 21),
("Leora Gleason", "https://s3.amazonaws.com/uifaces/faces/twitter/chrisslowik/128.jpg", 19),
("Mackenzie Shields", "https://s3.amazonaws.com/uifaces/faces/twitter/sunshinedgirl/128.jpg", 16),
("Francesca Hamill", "https://s3.amazonaws.com/uifaces/faces/twitter/bluefx_/128.jpg", 65),
("Kenyon Hoeger", "https://s3.amazonaws.com/uifaces/faces/twitter/areus/128.jpg", 73),
("Beaulah Frami", "https://s3.amazonaws.com/uifaces/faces/twitter/michaelmartinho/128.jpg", 32),
("Noah Rohan", "https://s3.amazonaws.com/uifaces/faces/twitter/h1brd/128.jpg", 1),
("Jay DuBuque", "https://s3.amazonaws.com/uifaces/faces/twitter/overra/128.jpg", 14),
("Alysa MacGyver", "https://s3.amazonaws.com/uifaces/faces/twitter/geneseleznev/128.jpg", 80),
("Lacy Collier", "https://s3.amazonaws.com/uifaces/faces/twitter/BrianPurkiss/128.jpg", 69),
("Magnolia Leannon", "https://s3.amazonaws.com/uifaces/faces/twitter/marclgonzales/128.jpg", 17),
("Caesar McLaughlin", "https://s3.amazonaws.com/uifaces/faces/twitter/andrewabogado/128.jpg", 69),
("Kaitlin Hickle", "https://s3.amazonaws.com/uifaces/faces/twitter/loganjlambert/128.jpg", 17),
("Damaris Quigley", "https://s3.amazonaws.com/uifaces/faces/twitter/jm_denis/128.jpg", 11),
("Lila Cronin", "https://s3.amazonaws.com/uifaces/faces/twitter/itolmach/128.jpg", 98),
("Roberta Gottlieb", "https://s3.amazonaws.com/uifaces/faces/twitter/brajeshwar/128.jpg", 52),
("Rasheed Harris", "https://s3.amazonaws.com/uifaces/faces/twitter/amywebbb/128.jpg", 47),
("Glenna Kshlerin", "https://s3.amazonaws.com/uifaces/faces/twitter/tweetubhai/128.jpg", 0),
("Burley McCullough", "https://s3.amazonaws.com/uifaces/faces/twitter/markjenkins/128.jpg", 77),
("Aric Connelly", "https://s3.amazonaws.com/uifaces/faces/twitter/a_brixen/128.jpg", 69),
("Torey Sawayn", "https://s3.amazonaws.com/uifaces/faces/twitter/duivvv/128.jpg", 56);